### ISSUE TITLE
version details about the project

### ISSUE THREAD

**Issue by NeuralFlux** [hrpan/tetris_mcts#5]
Hey, I literally wanted to try a combination of MCTS and TD learning on some retro games (inspiration from AlphaGo) and I stumbled upon your project. I'm excited to explore it and see if I can make a similar agent for different games. However, there seems to be an issue with **caffe2** and **PyTorch** installation, as my Python version (3.8) does not seem to have the versions mentioned in the requirements.txt

I have tried installing it with Python 3.8, 3.6 and 3.5 but **caffe2** just doesn't install (saying _0.8.1_ is not available). Even the version which is available (**caffe2** _0.5.0a0.dev100_) doesn't install due to some PyTorch issues. Could you please elaborate on what version of Python was used for this project? Also, did you have CUDA enabled for PyTorch (I have a CPU version 😞 )?

Thanks a lot for taking time to even read this stuff. I'd be very happy if I can just run your project on my PC.

**Comment by hrpan** [comment]
Hi,
I just checked my Python version and it shows 3.7.4.
As far as I know, caffe2 is no longer a standalone library, instead it is now integrated into PyTorch so you shouldn't need to install it explicitly.
I do have CUDA enabled for PyTorch but that should be optional unless I mistakenly hardcoded CUDA related stuff inside the code.
Let me know if you encounter any other problems!

**Comment by NeuralFlux** [comment]
Hey @hrpan , thanks a lot for the inputs. So I installed Python 3.7.4 and still ran into some issues (I luckily fixed them too 😝 ).
However, I discovered that I had to update **numba** to _0.49.1_ , as _0.45.1_ was giving some bugs.

I've also made a PR with the CUDA thing, please check it out as per your convenience 😄

**Comment by hrpan** [comment]
Thanks for the feedback, guess I should probably take some time to test the code and make sure things are working properly.

Also, thanks for the PR, I have approved it and merged it into master.

**Comment by NeuralFlux** [comment]
Glad I could contribute 😀
